version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: danangsukma/flask_app:0.1
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 25M
      restart_policy:
        condition: on-failure
    ports:
      - "5000:5000"
    networks:
      - webnet
networks:
  webnet: